name: memory_for_future
description: A futuristic memory assistant app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.4.0
  file_picker: ^5.2.5
  path: any
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  dotted_border: ^3.1.0
  intl: ^0.20.2
  url_launcher: ^6.1.12
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1

  # MediaKit dependencies for video playback on Windows
  media_kit: ^1.2.0
  media_kit_video: ^1.3.0
  media_kit_libs_windows_video: ^1.0.4

  flutter_neumorphic: ^3.2.0
  syncfusion_flutter_pdfviewer: ^30.1.41
  open_file: ^3.2.1
  mic_stream: ^0.7.2
  web_socket_channel: ^3.0.2
  just_audio: ^0.10.4
  async: ^2.10.0
  uuid: ^4.5.1
  flutter_sound: ^9.2.13
  flutter_dotenv: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
