name: memory_for_future
description: A futuristic memory assistant app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.4.0
  file_picker: ^5.2.5
  path: any
  fluttertoast: ^8.2.4
  google_fonts: ^6.2.1
  dotted_border: ^3.1.0
  intl: ^0.20.2
  url_launcher: ^6.1.12
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1
  # --- Media packages below ---
  media_kit: ^1.1.10
  media_kit_video: ^1.1.10
  media_kit_libs_windows_video: ^1.0.4
  flutter_neumorphic: ^3.2.0
  syncfusion_flutter_pdfviewer: ^30.1.41
  open_file: ^3.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

dependency_overrides:
  file_picker: ^5.2.5
