name: memory_for_future
description: A futuristic memory assistant app
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^0.13.6
  file_picker: ^5.2.5
  path: any
  fluttertoast: ^8.2.4
  google_fonts: ^4.0.4
  dotted_border: ^2.0.0
  intl: ^0.18.1
  url_launcher: ^6.1.12
  # ✅ Required for media handling and launcher
  video_player: ^2.7.0
  just_audio: ^0.9.34
  audioplayers: ^5.2.1
  flutter_pdfview: ^1.3.1
  path_provider: ^2.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  #assets:
   # - assets/

dependency_overrides:
  file_picker: ^5.2.5
